service: token-service
 
frameworkVersion: ">=2.0.0"
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  deploymentBucket:
    name: tokendeploymentbucket
plugins:
  - serverless-deployment-bucket

functions:
  token:
    handler: api/handler.submit
    memorySize: 128
    description: Submit Token