service: delete-bucket
 
frameworkVersion: ">=2.0.0"
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  deploymentBucket:
    name: selectdeletebucket
plugins:
  - serverless-deployment-bucket
functions:
  deleterbuck:
    handler: functions/handler.submit
    memorySize: 128
    description: Delete Objects Versions
    events:
      - http: 
          path: /buckdelete/{versionId}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                versionId: true 