service: s3-upload-text
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${file(config.example.json):STAGE}
  region: ${file(config.example.json):REGION}
  deploymentBucket:
    name: uploaddeploymentbuckettext
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${file(config.example.json):S3_BUCKET}/*"
plugins:
  - serverless-deployment-bucket
functions:
  createuploadgeturl:
    handler: functions/handler.createuploadtext
    events:
      - http:
          path: /object/{fileName}
          method: put
          cors: true
          request:
            parameters:
              paths:
                fileName: true 