service: bucket-version
 
frameworkVersion: ">=2.0.0"
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  deploymentBucket:
    name: deploymentversionbuck
plugins:
  - serverless-deployment-bucket

functions:
  bucketVersionSub:
    handler: api/handler.submit
    memorySize: 128
    description: Submit Bucket Version
    events:
      - http: 
          path: /buck/{fileName}
          method: get
          cors: true
          request:
            parameters:
              paths:
                fileName: true 